/********************************************************************
* tvoxeldict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error tvoxeldict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtabletvoxeldict();
extern void G__cpp_setup_inheritancetvoxeldict();
extern void G__cpp_setup_typetabletvoxeldict();
extern void G__cpp_setup_memvartvoxeldict();
extern void G__cpp_setup_globaltvoxeldict();
extern void G__cpp_setup_memfunctvoxeldict();
extern void G__cpp_setup_functvoxeldict();
extern void G__set_cpp_environmenttvoxeldict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "src/voxels/TVoxel.hpp"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__tvoxeldictLN_TClass;
extern G__linked_taginfo G__tvoxeldictLN_TBuffer;
extern G__linked_taginfo G__tvoxeldictLN_TMemberInspector;
extern G__linked_taginfo G__tvoxeldictLN_TObject;
extern G__linked_taginfo G__tvoxeldictLN_TArrayD;
extern G__linked_taginfo G__tvoxeldictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__tvoxeldictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__tvoxeldictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__tvoxeldictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__tvoxeldictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__tvoxeldictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__tvoxeldictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__tvoxeldictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__tvoxeldictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__tvoxeldictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__tvoxeldictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__tvoxeldictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__tvoxeldictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__tvoxeldictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__tvoxeldictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__tvoxeldictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__tvoxeldictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__tvoxeldictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__tvoxeldictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__tvoxeldictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__tvoxeldictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__tvoxeldictLN_TLorentzVector;
extern G__linked_taginfo G__tvoxeldictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__tvoxeldictLN_LArVox;
extern G__linked_taginfo G__tvoxeldictLN_LArVoxcLcLTVoxel;

/* STUB derived class for protected member access */
